### ISSUE TITLE
class level summary

### ISSUE THREAD

**Issue by wkeese** [wkeese/old-api-viewer#13]
Problems displaying class level summaries:
1. It's printing a "usage" section that is no longer accurate in the world of AMD:
   
   Usage:
   var foo = new dijit/Menu();
2. description not summary

It's only displaying the description, not the summary... so why do classes have both summaries and descriptions?

**Comment by ttrenka** [comment]
Summaries were always intended to be just that: a quick summary of what something represents.  This was intended for use in things like listings as opposed to a full-on look at a potential object.

On the usage thing...that's basically hardcoded, based on the original `<object location="foo.bar" />` expectation.  For the AMD world, I'd expect something more inline with how you'd use it.  In the original (in `lib/generate.php`, line 997+) it assumes that the object in question is how you'd actually call it.

**Comment by wkeese** [comment]
Ok... But can you show an example page (in the old API doc) where the
summary for a class is getting displayed?

**Comment by ttrenka** [comment]
On an object/class page, I didn't display summary, ever. `lib/generate.php`, original line 1018.

**Comment by wkeese** [comment]
I was just wondering if you displayed the summary anywhere else, like on the dijit page itself, or a tooltip when the Tree's nodes are hovered, etc.

**Comment by ttrenka** [comment]
You know, I didn't but I probably should have (original `generate.php`, starting at line 1090)...would have been in the list of "attached objects".
