### ISSUE TITLE
kwArgs expension seem to not end up at the right visual place

### ISSUE THREAD

**Issue by cjolif** [wkeese/old-api-viewer#16]
See for example the doc for dojox/charting/action2d/PlotAction constructor. The constructor say:

"An object with the following properties:

```
duration (Number, optional):

The amount of time in milliseconds for an animation to last. Default is 400.

easing
```

"

While it should be in the doc of the kwArgs attribute?

**Comment by wkeese** [comment]
The description of kwArgs is listed as though it were the constructor's summary.   details.xml looks OK.

OK I see, the viewer code incorrectly assumes that the first `<summary>` node which is a descendant of `<method>` is the method's summary, but in Colin's XML output the parameter summaries and descriptions precede the summary/description of the method itself.

**Comment by wkeese** [comment]
So it's really only half fixed, but I moved the remaining issue to csnover/js-doc-parse#53.

**Comment by cjolif** [comment]
thanks @wkeese
