### ISSUE TITLE
When using Permalinks, relative paths are broken

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#2]
When permalinking (e.g. `http://localhost/api/1.8/dijit/_Contained`) it appears the relative URIs do not work properly.

I am looking into this.

**Comment by wkeese** [comment]
Oh ok... Sounds like something that used to work but that I broke by
removing a bunch of $basePath/$baseUrl references from index.php.   I
didn't consider permalinks of that format.

I imported the svn history so you can see the diff of what I removed.

**Comment by kitsonk** [comment]
Fixed with commit: 37db9bc0f499973d41d8fb751318f3a2900ddd96

**Comment by wkeese** [comment]
(updated)

OK thanks... probably the default basePath should be "/api" instead of "", because probably people will have the API viewer as localhost/api.

What do you think?
