### ISSUE TITLE
add back the bug report link

### ISSUE THREAD

**Issue by wkeese** [wkeese/old-api-viewer#22]
Add the:

```
Error in the documentation? Can’t find what you are looking for? Let us know!
```

link that's at the bottom of http://dojotoolkit.org/api.

**Comment by ttrenka** [comment]
Just so you know, the version of /js/api.js in this repo is probably different from the one at dtk.org/api.  You can probably just drop in the dtk.org version and it should work as is (Colin put the bug reporting stuff in there).

**Comment by wkeese** [comment]
Well, it's too late for that now, but I'll grab the relevant change(s) from the DTK one, https://svn.dojotoolkit.org/infrastructure/sites/dojotoolkit.org/api
