### ISSUE TITLE
Command to blat the cache

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#26]
There should be something that can be run to blat the cache when "refreshing" the api-viewer.

**Comment by wkeese** [comment]
@ttrenka said there was already a command but I don't remember what it is.

Although you can avoid the problem while testing by not having a writable
cache directory.

**Comment by ttrenka** [comment]
Yeah, there's two things built in:
1. add ?clearcache=true to the URL to do it from the browser.
2. Enable/disable the cache through the config.php file.

**Comment by ttrenka** [comment]
I should add that the variable in question in config.php is $use_cache; set it to false if you want pages generated each time it gets hit.

**Comment by wkeese** [comment]
@kitsonk, is there any point to 5d80b8b when users can already clear the cache through the browser, via `?clearcache=true` ?

I don't know, maybe a script is better so that it can only be run by someone w/access to the server.

**Comment by kitsonk** [comment]
I didn't realise both things where there.  I will remove my stuff.

Also my blatting the cache, at the moment, is only UNIX like.

**Comment by ttrenka** [comment]
If it helps, when I was working on the viewer I always set `$use_cache` to false, although in general I did that in conjunction with re-parsing source code (i.e. changes in the documentation itself, not the viewer).
