### ISSUE TITLE
Undefined Index "topfunc"

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#28]
`generate.php` is incorrectly trying to determine an existence of a key in an array.  Currently is has:

``` php
if($obj["topfunc"]){
```

When in PHP it should be:

```
if(in_array("topfunc", $obj)){
```

(Also known as what happens when JS developers do PHP)

**Comment by wkeese** [comment]
Hmm, well the rest of the code uses array_key_exists(), perhaps that's better?

... yah, looks like in_array() is just wrong because it checks for a value, not a key, and this change breaks the display of the top function (ex: dojo/on) completely.   I'll check in a fix.
