### ISSUE TITLE
Improve RESTful API

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#3]
Improve/validate the RESTful API with Dojo 1.8 and rstWiki.

**Comment by wkeese** [comment]
One issue is that @csnover's parser is returning HTML rather than markdown (like the old parser did), which means that the JSON output of the restful service will have to contain HTML rather than markdown, which will probably flummox rstWiki.

**Comment by wkeese** [comment]
I don't know what you want to do here.   @lbod and I are planning to get rid of it completely, since you can just load the JSON file with all the data in it yourself.
