### ISSUE TITLE
Ability to Open Reference Guide from API Tree

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#40]
A request has been made to be able to open the Reference Guide from the Tree:

> Putting the link to the reference docs from the API docs was a fantastic
> move.  It really helps the learning process.  It's so useful, in fact, that
> I'd like to take it a step further and give some option to open both at the
> same time (if applicable) when clicking a link in the tree nav.  It's what I
> wind up doing now, anyway.  I don't think you'd have to clutter up the tree
> UI with more icons - just maybe something like ctrl+click opens both if
> applicable and just the doc tab if not.

**Comment by wkeese** [comment]
Yup, it seems like a good idea, perhaps just to open both pages in all cases.   But first need to fix https://github.com/phiggins42/rstwiki/issues/22, right?

**Comment by kitsonk** [comment]
Yes.  I will try to take a look at that one over the next couple of days.

**Comment by wkeese** [comment]
Thanks.   I wonder if there's a better UI than opening two tabs, like perhaps concatenating all the info into the same tab.   In any case, we need to start with the chromeless reference doc.
