### ISSUE TITLE
_base not showing up in 1.7 or 1.6 versions of the API viewer

### ISSUE THREAD

**Issue by dylans** [wkeese/old-api-viewer#46]
I believe we have a regression with our backwards compatibility support. Things like dojo/_base/ aren't showing up in the tree for the 1.7 and 1.6 versions of the API.

**Comment by wkeese** [comment]
Pre-1.8 the tree shows global variables like dojo.byId, not module id's
like dojo/_base/html.  Why would you expect dojo/_base to appear?
