### ISSUE TITLE
has() documentation

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#48]
This probably affects js-doc-parser as well, but we don't have any inline documentation for `has()` features.  I am not sure what is appropriate, but we should have something, as you have to simply "guess" at what the feature is.

**Comment by wkeese** [comment]
Yeah I agree, probably something to hack it into the existing infrastructure like having some fake module (similar to dojo/NodeList) where all the other modules that define flags add their definitions into that fake module.

**Comment by kitsonk** [comment]
Yeah, I guess that makes sense... extending the has object with each feature as a property?  Other modules that do a has.add() could do the same and then it would all collapse back to dojo/has.

**Comment by wkeese** [comment]
Yah.   Well, probably not the has object itself, but an object within it, like dojo/has.__Flags.
