### ISSUE TITLE
ReferenceError: location is not defined   

### ISSUE THREAD

**Issue by chitwarnold** [wkeese/old-api-viewer#50]
i cant seem to get anything working, i keep getting this Error, am trying to generate documentation for dojo 1.8 from the source files, and nothing. this is the complete error on the console

call55@maximus-pc:/opt/lampp/htdocs/js-doc-parse$ ./parse.sh /opt/lampp/htdocs/dojo1.8

/opt/lampp/htdocs/js-doc-parse/dojo/dojo.js:237
            var locationProtocol = location.protocol,
                                   ^
ReferenceError: location is not defined
    at hasCache.host-browser (/opt/lampp/htdocs/js-doc-parse/dojo/dojo.js:237:27)
    at Object.<anonymous> (/opt/lampp/htdocs/js-doc-parse/dojo/dojo.js:1789:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

NB:
js-doc-parse and the dojo src directory ( named dojo1.8)  are all located at my /opt/lampp/htdocs/ dir

my config file is under /opt/lampp/htdocs/js-doc-parse
with this code 

environmentConfig: {
        basePath: '/opt/lampp/htdocs/dojo1.8,
        packages: {
            dojo: 'dojo',
            dijit: 'dijit',
            dojox: 'dojox',
            doh: 'util/doh'
        },

nithing but the error?, also where do i plug the dependencies they are listed but i cant see where

**Comment by speich** [comment]
I'm having problems myself to get it running, so not that I know what the problem is, but if you are on windoze your basePath should be an absolute path and you should use backslashes and escape them.

**Comment by wkeese** [comment]
I don't know why you're getting that error either.   If anything though it's an issue with the doc parser (https://github.com/csnover/js-doc-parse) not the api viewer.

But I think if speich's advice doesn't work then you'll need to use a debugger (google debugging on node), and trace through to see what the problem is.   Or go low tech and add console.log's.

**Comment by chitwarnold** [comment]
waste of my time, stick to what i know for the current project, if anyone has a wrapped api kindly zip it and host it on github advice i will really benefit.i have YUI for the meanwhile

**Comment by chitwarnold** [comment]
yep 5 hours later and courtesy  of the - "There somethings only Dojo can do for me either that or raw js.."  yep managed to build the API in three different local sites each for the major packages (dojo,dijit,dojox), and this for me is better than nuthing and a huge step. thanks for the great tool,and sorry for the whinning,its what al newbies do. regards God Bless
