### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by dylans** [wkeese/old-api-viewer#56]
We receive many complaints that the API viewer does not work well on tablets or phones. Let's see if we can clean that up a bit after 1.9 is out.

**Comment by wkeese** [comment]
Please list out the complaints.   This ticket is too vague to take any action.

**Comment by dylans** [comment]
Try pulling the UI up on the iPad, as it's basically unusable:
- Tree does not scroll on mobile devices (no touch events?)
- Tapping an item from the tree does not display the API details on the right side
- Cannot see the legend details
- For the sections you can view (by clicking on the initial links on the right side of the UI), scrolling is rather slow

On the iPhone, to be useful, the tree would probably need to open each section in a new view, rather than trying to fit all of the details on the phone, but I think getting it at least working on the iPad would be a good first step.

**Comment by wkeese** [comment]
I see.  Actually all of these are working with the latest code, see http://bill.dojotoolkit.org/api/, except for the legend, which I'll fix now.

As for iPhone that sounds more like a separate app than a bug against this api-viewer.  Ideally it wouldn't be a Tree at all but a nested EdgeToEdgeList or something like that.
