### ISSUE TITLE
I hava a problem generating tree.json and details.xml..

### ISSUE THREAD

**Issue by jjcastano** [wkeese/old-api-viewer#57]
I'm trying to generate tree.json and details.xml with js-doc-parse (master branch) in MacOS but I always get the same problem when running parse.sh.

I have this folders with this configuration:
![folders](https://f.cloud.github.com/assets/3969214/308313/fe7f95dc-96e4-11e2-931b-11683bc45817.jpg)

And I get this error.. Any Ideas?:

{ [Error: multipleDefine]
  src: 'dojoLoader',
  info: 
   { pid: 'dojo',
     mid: 'dojo/node',
     pack: 
      { main: 'main',
        name: 'dojo',
        location: '/Users/jjcastano/Documents/BKS/code/juno-workspace/js-doc-parse/dojo' },
     url: '/Users/jjcastano/Documents/BKS/code/juno-workspace/js-doc-parse/dojo/node.js',
     executed: 0,
     def: [Function],
     isXd: undefined,
     isAmd: false,
     loadQ: [ [Object] ],
     injected: 'arrived',
     result: {},
     deps: [ [Object] ],
     cjs: 
      { id: 'dojo/node',
        uri: '/Users/jjcastano/Documents/BKS/code/juno-workspace/js-doc-parse/dojo/node.js',
        exports: {},
        setExports: [Function],
        config: [Function] } } }
src: dojoLoader
info: { pid: 'dojo',
  mid: 'dojo/node',
  pack: 
   { main: 'main',
     name: 'dojo',
     location: '/Users/jjcastano/Documents/BKS/code/juno-workspace/js-doc-parse/dojo' },
  url: '/Users/jjcastano/Documents/BKS/code/juno-workspace/js-doc-parse/dojo/node.js',
  executed: 0,
  def: [Function],
  isXd: undefined,
  isAmd: false,
  loadQ: 
   [ { plugin: [Circular],
       mid: 'dojo/node!9!waitingForPlugin',
       req: [Object],
       prid: 'path',
       injected: 'requested' } ],
  injected: 'arrived',
  result: {},
  deps: 
   [ { mid: 'exports',
       injected: 'arrived',
       executed: 'executed',
       def: 'not-a-module',
       result: 'not-a-module' } ],
  cjs: 
   { id: 'dojo/node',
     uri: '/Users/jjcastano/Documents/BKS/code/juno-workspace/js-doc-parse/dojo/node.js',
     exports: {},
     setExports: [Function],
     config: [Function] } }

**Comment by wkeese** [comment]
> I'm trying to generate tree.json and details.xml with js-doc-parse (master branch) in MacOS

That's not supposed to work.    As the instructions (https://github.com/wkeese/api-viewer) say, you need to use the all-my-changes branch.
