### ISSUE TITLE
ERR:  TypeError: Object true has no method 'match'

### ISSUE THREAD

**Issue by shioyang** [wkeese/old-api-viewer#59]
The following error occurs, when I issued "parse.bat config=./config.js".
How can I resolve this problem? I would appreciate if you could give some advice.

> C:\LocalProgramFiles\js-doc-parse>parse.bat config=./config.js
> 
> C:\LocalProgramFiles\js-doc-parse>node parse.js config
> ERR:  TypeError: Object true has no method 'match'
>     at getModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1010:16)
>     at contextRequire (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:767:17)
>     at result (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:808:13)
>     at C:/LocalProgramFiles/js-doc-parse/lib/env.js:249:2
>     at runFactory (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1094:43)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1223:5)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1214:12)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1214:12)
>     at C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1258:6
>     at guardCheckComplete (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1238:5)

I did on command prompt with Admin:
        $ git clone --recursive https://github.com/wkeese/js-doc-parse.git
        $ cd js-doc-parse
        $ git checkout all-my-changes
        $ [Edit config.js: configure basePath and replace \ to \\]
        $ parse.bat config=./config.js

Env:
Win7 64 (UAC disabled)
js-doc-parse: latest commit

**Comment by wkeese** [comment]
I tried pulling the latest code from csnover, and uploaded to https://github.com/wkeese/js-doc-parse.git.   You can try again.   Latest changes are on master branch, not the all-my-changes branch.

**Comment by shioyang** [comment]
Hi, thank you for your reply.

I removed all files and tried again. At this time, I just issue "git clone --recursive https://github.com/csnover/js-doc-parse.git" and "parse.bat config=./config".
A same problem happened...

> C:\LocalProgramFiles\js-doc-parse>parse.bat config=./config.js
> ERR:  TypeError: Object true has no method 'match'
>     at getModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1010:16)
>     at contextRequire (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:767:17)
>     at result (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:808:13)
>     at C:/LocalProgramFiles/js-doc-parse/lib/env.js:250:2
>     at runFactory (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1094:43)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1223:5)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1214:12)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1214:12)
>     at C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1258:6
>     at guardCheckComplete (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1238:5)

**Comment by wkeese** [comment]
OK sorry, I never use windows anymore so I don't know how to make that work.   As you can see from changes like https://github.com/csnover/js-doc-parse/commit/6ac54c4cdc4e8fbd25214c93c49cff30cb75d6c8 parse.bat is apparently working for some people.   Maybe you can ask them.

**Comment by shioyang** [comment]
I see. I will post it to csnover/js-doc-parse. Thank you.
