### ISSUE TITLE
js-doc-parse 'all-my-changes' branch has git merge issues 

### ISSUE THREAD

**Issue by zemanel** [wkeese/old-api-viewer#60]
the documentation generation instructions refer to the 'all-my-changes' branch of

https://github.com/wkeese/js-doc-parse/

but the 'all-my-changes' branch has issues with a badly merged branch ("<<<<<<< HEAD" artifacts):

https://github.com/wkeese/js-doc-parse/blob/all-my-changes/lib/exporter/dojov1.js#L287

**Comment by wkeese** [comment]
OK, I moved my changes to the master branch and updated the instructions.   The bad merge seems to be gone.
