### ISSUE TITLE
API viewer not displaying docs

### ISSUE THREAD

**Issue by chrisfelix82** [wkeese/old-api-viewer#62]
I have installed the api viewer.  I am able to load the tree, but when I click on a file, I see a 404.  e.g. http://<server>/api/apidata/1.0/commonapp/welcome/testView.

WHy is it looking for the docs in apidata at that level.  I thought it was suppose to look in api_data - the sibling of api directory.  What am I missing??

Thanks

**Comment by wkeese** [comment]
Sorry, I don't know why it's not working for you.   The directory is controlled through config.php via that $dataDir variable.   You need to trace from there.
