### ISSUE TITLE
API viewer used by dojotoolkit.org

### ISSUE THREAD

**Issue by Kapeli** [wkeese/old-api-viewer#64]
Is this the same API viewer used by dojotoolkit.org?

I'm trying to convert the docs to a format that my app ([Dash](http://kapeli.com/dash)) understands, but I'm not able to grab the content of the docs anymore.

The generation script I have traverses http://dojotoolkit.org/api/data/1.10/tree.json and grabs the content of the pages from URLs like http://dojotoolkit.org/api/lib/item.php?p=dijit/_base/focus&v=1.10. Unfortunately, http://dojotoolkit.org/api/lib/item.php seems to be a 404 now.

I see that https://github.com/wkeese/old-api-viewer/blob/master/lib/item.php still exists in this git repo, so my best guess is that dojotoolkit.org isn't running this API viewer anymore?

Thanks for the help!

**Comment by wkeese** [comment]
> Is this the same API viewer used by dojotoolkit.org?

No, it's not, as the description for this project says, it's the old viewer for output of old js-doc-parse, replaced by https://github.com/lbod/dapi.
