### ISSUE TITLE
Need to add current dojotoolkit.org Theme

### ISSUE THREAD

**Issue by kitsonk** [wkeese/old-api-viewer#9]
The current `dtk` theme does not match the current dojotoolkit.org theme.  A new one needs to be created.

**Comment by ttrenka** [comment]
The version of the API viewer at dtk.org has this theme already in place; the name of the theme must be set in the config.php file, and there should be a matching directory under /themes.  The only file that is truly affected is /index.php (iirc there's been some slight modifications to it directly in the dtk.org repo, but those mods are minor.)
